### ISSUE TITLE
dracut-install error

### ISSUE THREAD

**Issue by brunommpreto** [ryncsn/memstrack#10]
After a `sudo make dacrut-module-install` and performing a `sudo mkinitrd` and get the following error

> `dracut: *** Including module: memstrack ***
> dracut-install: ERROR: installing '/bin/memstrack' to '/bin/memstrack'
> dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.3fhmog/initramfs /bin/memstrack /bin/memstrack
> `

**Comment by ryncsn** [comment]
Hmm, that's strange, does the file /bin/memstrack exists? Do you have the full log of running "make dacrut-module-install"? I've pushed a new commit to avoid the hard-coded installation source in dracut module, you can have a try.
