### ISSUE TITLE
README: Installation: add Arch Linux install info for memstrack

### ISSUE THREAD

**Issue by barmadrid** [ryncsn/memstrack#12]
I packaged `memstrack` for Arch Linux, both stable release and git version. Consider adding below in README section, if that's not a problem 😊

In Arch Linux, [memstrack](https://aur.archlinux.org/packages/memstrack/) and [memstrack-git](https://aur.archlinux.org/packages/memstrack-git/) packages are both available in the [AUR](https://aur.archlinux.org/)

To install, you can either use an [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers) or follow the manual procedure as follows:

Clone the package:
```
$ git clone https://aur.archlinux.org/packages/memstrack/`
```
Finally build and install the application:
```
$ cd memstrack
$ makepkg -si
```
Done!

**Comment by ryncsn** [comment]
Thank you! I've added it in README :)
