### ISSUE TITLE
wanna use it on arm

### ISSUE THREAD

**Issue by hellodword** [ryncsn/memstrack#9]
It'll be great with arm32 and arm64 static releases.

**Comment by ryncsn** [comment]
It should work on arm if you clone and build it your self, I've tested that before. I'll add a release to add arm build as well.

**Comment by hellodword** [comment]
> It should work on arm if you clone and build it your self, I've tested that before. I'll add a release to add arm build as well.

Thanks that's nice.

**Comment by hellodword** [comment]
resolved in https://github.com/ryncsn/memstrack/commit/1d21b6985b61f88633776592f80742fc5eb62bcf

thx
